-- AlterTable
ALTER TABLE "puzzles" ADD COLUMN     "xpReward" INTEGER NOT NULL DEFAULT 50;

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "level" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "xp" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "xpTitle" TEXT NOT NULL DEFAULT 'Newcomer';
