import { NextResponse } from "next/server";

// Day 1 = 2026-03-31 (launch day)
const START_DATE = Date.UTC(2026, 2, 31); // month is 0-indexed

const WORDS = [
  "ADEPT","AGILE","ALARM","ALBUM","ALERT","ALGAE","ALIBI","ALIEN","ALOFT","AMBLE",
  "AMEND","AMPLE","ANGEL","ANIME","ANKLE","ANNEX","ANTIC","ANVIL","AORTA","APHID",
  "APPLE","APRON","APTLY","ARBOR","ARDOR","ARENA","ARGON","AROMA","AROSE","ARROW",
  "ARTSY","ASCOT","ASDIC","ASHEN","ASKEW","ATLAS","ATONE","ATTIC","AUDIT","AVAIL",
  "AVIAN","AVOID","AWASH","AWFUL","AWOKE","AXIOM","AZURE","BADGE","BALMY","BANAL",
  "BARGE","BARON","BASIL","BATON","BAYOU","BEACH","BEARD","BEAST","BEGIN","BEIGE",
  "BENCH","BEVEL","BIRCH","BISON","BLADE","BLAND","BLAZE","BLEAK","BLISS","BLOAT",
  "BLOKE","BLOOD","BLOOM","BLOWN","BLUFF","BLUNT","BLURB","BLURT","BLUSH","BONGO",
  "BONUS","BOOST","BORAX","BOXER","BRAID","BRAIN","BRAKE","BRAND","BRASH","BRASS",
  "BRAVE","BRAVO","BRAWN","BRAZE","BREAM","BRINE","BRINK","BRINY","BRISK","BROOD",
  "BROTH","BROWS","BUDGE","BULKY","BULLY","BUNCH","BUNNY","BURST","BYLAW","CADET",
  "CAMEL","CANDY","CARGO","CAROL","CEDAR","CHAOS","CHARM","CHEAP","CHEAT","CHECK",
  "CHESS","CHEST","CHEWY","CHILI","CINCH","CIVIC","CLAMP","CLASP","CLING","CLOAK",
  "CLONE","CLOUD","CLOVE","COBRA","COMET","CORAL","COULD","COURT","CRAMP","CRANE",
  "CRASH","CREAK","CREED","CRIMP","CRISP","CROAK","CROOK","CROSS","CRYPT","CURVE",
  "DELTA","DENSE","DEPOT","DEPTH","DIGIT","DINGO","DIZZY","DODGE","DREAD","DRIFT",
  "DRILL","DRIVE","DROLL","DRONE","DROOL","DROVE","DRUMN","DUSKY","DUSTY","DWARF",
  "EAGLE","EERIE","EIGHT","ELECT","ELITE","EMBER","ENVOY","EPOCH","EQUIP","ETHOS",
  "EVADE","EVENT","EVICT","EXACT","EXCEL","EXERT","EXILE","EXPEL","EXTRA","FABLE",
  "FACET","FAITH","FANCY","FATWA","FEAST","FERAL","FERRY","FETCH","FJORD","FLAME",
  "FLANK","FLARE","FLASK","FLEET","FLINT","FLOAT","FLORA","FLOSS","FLUKE","FLUTE",
  "FORAY","FORGE","FORUM","FRAIL","FRAME","FRESH","FROTH","FROZE","FUNGI","GAUZE",
  "GAVEL","GECKO","GHOUL","GIANT","GIRTH","GIZMO","GLADE","GLARE","GLEAN","GLOOM",
  "GLOSS","GLOVE","GLYPH","GNASH","GORGE","GRACE","GRAIL","GRIME","GRIPE","GROAN",
  "GROUT","GROWL","GRUFF","GUILE","GUSTO","GYPSY","HAIKU","HARDY","HARSH","HASTE",
  "HAUNT","HAVEN","HELIX","HERON","HIPPO","HOIST","HOLLY","HOMER","HOUND","HOUSE",
  "HUMAN","HUMID","HYENA","IDEAL","IDYLL","IMAGE","IMPLY","INBOX","INEPT","INFER",
  "INGOT","INPUT","IRONY","IVORY","JAUNT","JAZZY","JEWEL","JIFFY","JOUST","JUICY",
  "JUMBO","KIOSK","KNACK","KNELT","KNOLL","KUDOS","LANCE","LAPSE","LARGE","LASER",
  "LATCH","LATHE","LEAKY","LEAPT","LEARN","LEDGE","LIGHT","LILAC","LLAMA","LOCAL",
  "LOFTY","LUNAR","LUSTY","LYRIC","MAGIC","MANOR","MAXIM","MAUVE","MELON","MERCY",
  "MIRTH","MOIST","MONTH","MOOSE","MORSE","MOTOR","MOUNT","MURKY","MURAL","NAIVE",
  "NEXUS","NIGHT","NINJA","NITRO","NIFTY","NOBLE","NOTCH","NOVEL","NYMPH","OCCUR",
  "OCEAN","OKAPI","OLIVE","ONSET","OPTIC","ORBIT","OTHER","OZONE","PEACE","PENNY",
  "PERCH","PERKY","PIECE","PILOT","PIXEL","PLACE","PLAID","PLANE","PLUMB","PLUME",
  "POLAR","PRANK","PRIME","PRISM","PRIVY","PROBE","PROXY","PSALM","PURSE","QUEEN",
  "QUERY","QUEST","QUEUE","QUIRK","QUOTA","RABID","RAINY","RAVEN","REBEL","RELIC",
  "RESIN","RIVET","ROCKY","ROGUE","ROOST","ROYAL","RUDDY","RULER","RUMMY","RURAL",
  "SCAMP","SCALP","SCONE","SCOUT","SHADE","SHAKE","SHAME","SHARP","SHEEP","SHIFT",
  "SHRUB","SIEGE","SIREN","SIXTY","SKUNK","SLEET","SLIM","SLOPE","SLUNK","SMASH",
  "SMEAR","SMILE","SMOKE","SNAKE","SOLAR","SOLVE","SOOTH","SPADE","SPARK","SPEAR",
  "SPELL","SPICE","SPIRE","SPOKE","SPOOK","SPOOL","SPOUT","SPRAY","STALE","STALK",
  "STASH","STEAK","STEED","STERN","STING","STOMP","STORM","STRAP","SWAMP","SWEAR",
  "SWEPT","TABOO","TACIT","TAPIR","TARDY","TAWNY","THEME","THORN","TIGER","TITLE",
  "TOKEN","TORCH","TRAIL","TRAWL","TRIPE","TROUT","TRYST","TULIP","TURBO","TWIRL",
  "ULCER","ULTRA","UMBRA","UNITY","UNTIE","USHER","VALID","VAULT","VENOM","VERGE",
  "VERVE","VIGOR","VINYL","VIPER","VIVID","VOICE","VYING","WALTZ","WATER","WEAVE",
  "WHALE","WHACK","WHEAT","WITCH","WOKEN","WRATH","YACHT","YEARN","YIELD","ZESTY",
];

export async function GET() {
  const now = new Date();
  const todayUtc = Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate());
  const dayNumber = Math.floor((todayUtc - START_DATE) / 86_400_000) + 1;
  const word = WORDS[((dayNumber - 1) % WORDS.length + WORDS.length) % WORDS.length];
  const date = now.toISOString().slice(0, 10);

  return NextResponse.json(
    { word, number: dayNumber, date },
    {
      headers: {
        // Cache until midnight UTC
        "Cache-Control": "public, max-age=0, s-maxage=86400, stale-while-revalidate=60",
      },
    }
  );
}
